sudo: required
dist: trusty 

before_install:
  - cat /etc/apt/sources.list
  - echo "deb http://archive.ubuntu.com/ubuntu precise-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y lxd

language: generic
# python:
#  - "2.6"
script: ./tests/test1.py
